### ISSUE TITLE
GTDB doesn't recognize fasta assembly type input

### ISSUE THREAD

**Issue by ghost** [kbaseapps/kb_gtdbtk#91]
I added two fasta files with contigs in my KBASE narrative and assigned them to FASTA assembly type, but GTDB does not recognize my input. Am I doing something wrong?
![Captura de tela 2024-01-12 160728](https://github.com/kbaseapps/kb_gtdbtk/assets/36411112/4506378f-0189-42b2-86dd-89d04e08df44)

**Comment by kmmarcello** [comment]
This is 7 mo later, but I am also having this issue. Did you ever get it resolved?

**Comment by crockettz** [comment]
Hi @kmmarcello,
This new version only takes "set-like" inputs - GenomeSets, AssemblySets, or BinnedContigs. That tradeoff is a design choice to streamline job submissions of 1 set rather than a bunch of individual jobs, but it comes at the expense of cases like yours where there is only 1 or 2. You'll need to create a set which contains those assemblies using the Build AssemblySet app, and then input that AssemblySet into GTDB.

**Comment by kmmarcello** [comment]
thank you @crockettz, this worked!

**Comment by silviacretoiu** [comment]
Hello, I'm looking for a solution to use the app. I have an assembly set containing 24 SPAdes assemblies and I'm keep getting this error: 

Traceback (most recent call last):
  File "/kb/module/bin/../lib/kb_gtdbtk/kb_gtdbtkServer.py", line 101, in _call_method
    result = method(ctx, *params)
  File "/kb/module/lib/kb_gtdbtk/kb_gtdbtkImpl.py", line 174, in run_kb_gtdbtk_classify_wf
    (classification, summary_tables) = run_gtdbtk (runner,
  File "/kb/module/lib/kb_gtdbtk/core/gtdbtk_runner.py", line 131, in run_gtdbtk
    return _process_output_files(temp_output, temp_trees_output, output_dir, id_to_name)
  File "/kb/module/lib/kb_gtdbtk/core/gtdbtk_runner.py", line 268, in _process_output_files
    if row[field_i] == 'N/A':
IndexError: list index out of range
